import { Handyman, PricingPlan } from './types';
import { Filter, Sparkles, Home, Car, Droplets, Zap, Hammer, Paintbrush, Wind, Scissors, LayoutGrid, Wrench, Hand, Footprints, Sprout, Cpu, Tv, Eye, PenTool, Battery, Waves, Radio, Scale, Truck, BookOpen, Calculator } from 'lucide-react';
// --- Mock Data ---
export const PLACEHOLDER_WORK_IMAGE = 'https://placehold.co/400x300/f1f5f9/64748b?text=Previous+Work';

export const INITIAL_HANDYMEN: Handyman[] = [
  {
    id: '1',
    name: 'Chinedu Okoro',
    category: 'Plumbing',
    location: 'Lagos Island, Lagos',
    lat: 6.4549,
    lng: 3.4246,
    rating: 4.8,
    reviews: 24,
    phone: '08012345678',
    whatsapp: '2348012345678',
    experience: '10 years',
    experienceYears: 10,
    verified: true,
    ninVerified: true,
    isFeatured: true,
    isOnline: true,
    description: 'Specialist in modern bathroom fittings and industrial piping. Available for emergency leaks 24/7.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
    plan: 'pro'
  },
  {
    id: '2',
    name: 'Abubakar Musa',
    category: 'Electrical',
    location: 'Wuse II, Abuja',
    lat: 9.0765,
    lng: 7.4985,
    rating: 4.5,
    reviews: 18,
    phone: '08087654321',
    whatsapp: '2348087654321',
    experience: '7 years',
    experienceYears: 7,
    verified: true,
    isFeatured: true,
    isOnline: false,
    description: 'Certified electrician for home wiring, inverter installations, and generator maintenance.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
    plan: 'pro'
  },
  {
    id: '3',
    name: 'Oluwaseun Adeyemi',
    category: 'Carpentry',
    location: 'Ibadan, Oyo',
    lat: 7.3775,
    lng: 3.9470,
    rating: 4.9,
    reviews: 32,
    phone: '07011223344',
    experience: '15 years',
    experienceYears: 15,
    verified: true,
    isOnline: true,
    description: 'Master craftsman for bespoke furniture, kitchen cabinets, and roofing.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
    plan: 'basic'
  },
  {
    id: '4',
    name: 'Funke Akindele',
    category: 'Painting',
    location: 'Lekki Phase 1, Lagos',
    lat: 6.4478,
    lng: 3.4723,
    rating: 4.7,
    reviews: 15,
    phone: '08122334455',
    experience: '6 years',
    experienceYears: 6,
    verified: true,
    isOnline: true,
    description: 'Professional interior and exterior painting. Specialist in decorative finishes and wallpaper installation.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
    plan: 'pro'
  },
  {
    id: '5',
    name: 'Emeka Nwosu',
    category: 'General Repairs',
    location: 'Independence Layout, Enugu',
    lat: 6.4584,
    lng: 7.5083,
    rating: 4.4,
    reviews: 12,
    phone: '09011223344',
    experience: '5 years',
    experienceYears: 5,
    verified: false,
    isOnline: true,
    description: 'Handyman for all your home maintenance needs. From door locks to minor masonry and tiling.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
    plan: 'basic'
  },
  {
    id: '6',
    name: 'Ibrahim Danjuma',
    category: 'Mechanic',
    location: 'Kano City, Kano',
    lat: 12.0022,
    lng: 8.5920,
    rating: 4.6,
    reviews: 29,
    phone: '08033445566',
    whatsapp: '2348033445566',
    experience: '8 years',
    experienceYears: 8,
    verified: true,
    isOnline: true,
    description: 'Expert in Japanese and German engines. Computerized diagnostics available.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '7',
    name: 'Tunde Bakare',
    category: 'AC Technician',
    location: 'GRA Phase 2, Port Harcourt',
    lat: 4.8156,
    lng: 7.0498,
    rating: 4.8,
    reviews: 41,
    phone: '08144556677',
    experience: '9 years',
    experienceYears: 9,
    verified: true,
    isOnline: true,
    description: 'Specialist in split and central AC systems. Gas refilling, servicing, and installation.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '8',
    name: 'Amina Yusuf',
    category: 'Tailor',
    location: 'Barnawa, Kaduna',
    lat: 10.5105,
    lng: 7.4165,
    rating: 4.9,
    reviews: 53,
    phone: '07055667788',
    experience: '12 years',
    experienceYears: 12,
    verified: true,
    isOnline: false,
    description: 'Expert in traditional and corporate wears. Custom designs for weddings and special occasions.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '9',
    name: 'Sunday Udoh',
    category: 'Bricklayer',
    location: 'Ewet Housing, Uyo',
    lat: 5.0333,
    lng: 7.9266,
    rating: 4.5,
    reviews: 21,
    phone: '08066778899',
    experience: '20 years',
    experienceYears: 20,
    verified: true,
    isOnline: true,
    description: 'Master bricklayer for building construction, fencing, and interlocking stones.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '10',
    name: 'Maryam Bello',
    category: 'House Help',
    location: 'Rayfield, Jos',
    lat: 9.8965,
    lng: 8.8583,
    rating: 4.7,
    reviews: 38,
    phone: '09077889900',
    experience: '6 years',
    experienceYears: 6,
    verified: true,
    isOnline: true,
    description: 'Reliable house help for laundry, cooking, and general home management. Vetted and trustworthy.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '11',
    name: 'Blessing Egbe',
    category: 'Cleaning',
    location: 'Victoria Island, Lagos',
    lat: 6.4281,
    lng: 3.4215,
    rating: 4.7,
    reviews: 64,
    phone: '08033221100',
    whatsapp: '2348033221100',
    experience: '4 years',
    experienceYears: 4,
    verified: true,
    isOnline: false,
    description: 'Professional deep cleaning for homes and offices. Eco-friendly products used.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '12',
    name: 'Kayode Williams',
    category: 'Auto Services',
    location: 'Bodija, Ibadan',
    lat: 7.4144,
    lng: 3.9105,
    rating: 4.6,
    reviews: 19,
    phone: '08188990011',
    experience: '7 years',
    experienceYears: 7,
    verified: false,
    isOnline: true,
    description: 'Comprehensive auto services including wheel balancing, alignment, and brake repairs.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
    plan: 'pro'
  },
  {
    id: '13',
    name: 'Sarah Johnson',
    category: 'Manicure',
    location: 'Surulere, Lagos',
    lat: 6.5000,
    lng: 3.3500,
    rating: 4.9,
    reviews: 45,
    phone: '08099887766',
    experience: '5 years',
    experienceYears: 5,
    verified: true,
    isOnline: true,
    description: 'Expert in gel polish, acrylics, and nail art. Clean and professional service.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '14',
    name: 'Grace Udoh',
    category: 'Pedicure',
    location: 'Ikeja, Lagos',
    lat: 6.5967,
    lng: 3.3421,
    rating: 4.8,
    reviews: 32,
    phone: '08122334455',
    experience: '4 years',
    experienceYears: 4,
    verified: true,
    isOnline: true,
    description: 'Professional pedicure and foot spa. Relaxing and hygienic treatment.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '15',
    name: 'David Okeke',
    category: 'Barber',
    location: 'Enugu City, Enugu',
    lat: 6.4413,
    lng: 7.4988,
    rating: 4.7,
    reviews: 89,
    phone: '09033445566',
    experience: '8 years',
    experienceYears: 8,
    verified: true,
    isOnline: true,
    description: 'Master barber for all hair types. Clean fades and sharp outlines.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '16',
    name: 'Aisha Mohammed',
    category: 'Hairstylist',
    location: 'Maitama, Abuja',
    lat: 9.0765,
    lng: 7.4985,
    rating: 4.9,
    reviews: 120,
    phone: '08011223344',
    experience: '10 years',
    experienceYears: 10,
    verified: true,
    isOnline: true,
    description: 'Specialist in braids, wigs, and natural hair care. Home service available.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '17',
    name: 'Babatunde Ojo',
    category: 'Horticulturist',
    location: 'Ikeja, Lagos',
    lat: 6.5967,
    lng: 3.3421,
    rating: 4.8,
    reviews: 27,
    phone: '08133445566',
    experience: '12 years',
    experienceYears: 12,
    verified: true,
    isOnline: true,
    description: 'Professional landscaping and garden maintenance. Specialist in tropical plants and lawn care.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '18',
    name: 'Linda Eze',
    category: 'Manicure',
    location: 'Enugu City, Enugu',
    lat: 6.4413,
    lng: 7.4988,
    rating: 4.7,
    reviews: 18,
    phone: '08022334455',
    experience: '3 years',
    experienceYears: 3,
    verified: false,
    isOnline: true,
    description: 'Mobile nail technician specializing in acrylic extensions and luxury manicures.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '19',
    name: 'Segun Barber',
    category: 'Barber',
    location: 'Ibadan, Oyo',
    lat: 7.3775,
    lng: 3.9470,
    rating: 4.6,
    reviews: 54,
    phone: '08155667788',
    experience: '15 years',
    experienceYears: 15,
    verified: true,
    isOnline: true,
    description: 'Veteran barber with expertise in all traditional and modern cuts. Home service available.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '20',
    name: 'Kemi Braids',
    category: 'Hairstylist',
    location: 'Lekki, Lagos',
    lat: 6.4478,
    lng: 3.4723,
    rating: 4.9,
    reviews: 76,
    phone: '07033445566',
    experience: '7 years',
    experienceYears: 7,
    verified: true,
    isOnline: true,
    description: 'Specialist in knotless braids, cornrows, and hair extensions. Fast and neat.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '21',
    name: 'Obinna Tattoos',
    category: 'Tattoo artist',
    location: 'Surulere, Lagos',
    lat: 6.5000,
    lng: 3.3500,
    rating: 4.9,
    reviews: 42,
    phone: '08011223344',
    whatsapp: '2348011223344',
    experience: '6 years',
    experienceYears: 6,
    verified: true,
    isOnline: true,
    description: 'Professional tattoo artist specializing in realism, traditional African patterns, and fine line work. Sterile and safe environment.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
    plan: 'pro'
  },
  {
    id: '22',
    name: 'Chinedu Obi',
    category: 'Generator Repair',
    location: 'Lekki Phase 1, Lagos',
    lat: 6.4483,
    lng: 3.4767,
    rating: 4.8,
    reviews: 56,
    phone: '08022334455',
    experience: '6 years',
    experienceYears: 6,
    verified: true,
    isOnline: true,
    description: 'Expert in Mikano, Perkins, and Tiger generators. Quick response and reliable service.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '23',
    name: 'Suleiman Danjuma',
    category: 'Satellite Installer',
    location: 'Gwarinpa, Abuja',
    lat: 9.1000,
    lng: 7.4000,
    rating: 4.7,
    reviews: 42,
    phone: '08133445566',
    experience: '5 years',
    experienceYears: 5,
    verified: true,
    isOnline: true,
    description: 'Professional installation of DSTV, GOTV, and StarTimes. Signal optimization and mounting.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  },
  {
    id: '24',
    name: 'Kingsley Shoes',
    category: 'Shoe Maker',
    location: 'Yaba, Lagos',
    lat: 6.5095,
    lng: 3.3711,
    rating: 4.8,
    reviews: 35,
    phone: '08123456789',
    experience: '8 years',
    experienceYears: 8,
    verified: true,
    isOnline: true,
    description: 'Expert shoe cobbler and leather works. Repair, design, and shining.',
    portfolio: [PLACEHOLDER_WORK_IMAGE, PLACEHOLDER_WORK_IMAGE],
  }
];



export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'basic',
    name: 'Starter',
    price: 'Free',
    period: 'for first 2 leads',
    features: [
      'Standard Listing',
      'Basic Profile',
      '2 Welcome Credits',
      'Pay-per-Lead after trial',
      'Community Support'
    ],
    buttonText: 'Get Started'
  },
  {
    id: 'credits-1',
    name: 'Single Lead',
    price: '₦1,000',
    period: 'one-time',
    features: [
      '1 Credit',
      'Unlock 1 Lead',
      'No Expiry'
    ],
    buttonText: 'Buy 1 Credit'
  },
  {
    id: 'credits-10',
    name: 'Starter Pack',
    price: '₦7,500',
    period: 'one-time',
    features: [
      '10 Credits',
      'Unlock 10 Leads',
      'Save ₦2,500',
      'No Expiry'
    ],
    buttonText: 'Buy 10 Credits'
  },
  {
    id: 'credits-50',
    name: 'Growth Pack',
    price: '₦30,000',
    period: 'one-time',
    features: [
      '50 Credits',
      'Unlock 50 Leads',
      'Save ₦20,000',
      'Priority Support',
      'No Expiry'
    ],
    buttonText: 'Buy 50 Credits'
  },
  {
    id: 'pro',
    name: 'Featured Pro',
    price: '₦10,000',
    period: 'per month',
    features: [
      'Featured Badge',
      'Top of Search Results',
      'Verified Status Badge',
      'Priority Lead Notifications',
      'Analytics Dashboard'
    ],
    recommended: true,
    buttonText: 'Go Featured'
  },
  {
    id: 'member',
    name: 'Customer Member',
    price: '₦2,500',
    period: 'per month',
    features: [
      'Access Verified Pros Only',
      'Priority Support',
      'Community Guarantee',
      'Exclusive Discounts',
      'No Ads'
    ],
    buttonText: 'Join Community'
  },
  {
    id: 'enterprise',
    name: 'Agency',
    price: '₦50,000',
    period: 'per month',
    features: [
      'Up to 10 Team Members',
      'Advanced SEO Optimization',
      'Dedicated Account Manager',
      'Custom Portfolio URL',
      'Bulk SMS Marketing',
      'Unlimited Lead Unlocks'
    ],
    buttonText: 'Contact Sales'
  }
];

export const CATEGORIES = [
  { name: 'All', icon: Filter },
  { name: 'Cleaning', icon: Sparkles },
  { name: 'House Help', icon: Home },
  { name: 'Auto Services', icon: Car },
  { name: 'Plumbing', icon: Droplets },
  { name: 'Electrical', icon: Zap },
  { name: 'Carpentry', icon: Hammer },
  { name: 'Painting', icon: Paintbrush },
  { name: 'Mechanic', icon: Car },
  { name: 'AC Technician', icon: Wind },
  { name: 'Tailor', icon: Scissors },
  { name: 'Bricklayer', icon: LayoutGrid },
  { name: 'General Repairs', icon: Wrench },
  { name: 'Manicure', icon: Hand },
  { name: 'Pedicure', icon: Footprints },
  { name: 'Hairstylist', icon: Scissors },
  { name: 'Barber', icon: Scissors },
  { name: 'Horticulturist', icon: Sprout },
  { name: 'Tattoo artist', icon: PenTool },
  { name: 'Generator Repair', icon: Zap },
  { name: 'Inverter Specialist', icon: Battery },
  { name: 'Borehole Driller', icon: Waves },
  { name: 'Satellite Installer', icon: Radio },
  { name: 'Lawyer', icon: Scale },
  { name: 'Accountant', icon: Calculator },
  { name: 'House Removal', icon: Truck },
  { name: 'Home Tutor', icon: BookOpen },
  { name: 'Shoe Maker', icon: Footprints },
];

// --- Helpers ---
export function deg2rad(deg: number) {
  return deg * (Math.PI / 180);
}

export function getDistance(lat1: number, lon1: number, lat2: number, lon2: number) {
  const R = 6371; // Radius of the earth in km
  const dLat = deg2rad(lat2 - lat1);
  const dLon = deg2rad(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) *
    Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const d = R * c; // Distance in km
  return d;
}
export const calculateDistance = (lat1: number, lon1: number, lat2: number, lon2: number) => {
  const R = 6371; // km
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
            Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
            Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
};

